### PR TITLE
Solve all notes and warns from R CMD check

### PR DESCRIPTION
**Pull request by zzawadz**
Having those changes should bring the package closer to CRAN release. The next step will be to check the package with the current devel version (which I can easily do).

### CODE REVIEW

**Comment by zzawadz** [comment]
Unfortunately, the timeouts are quite common when testing with --as-cran. I think, it might be wise to make those timeouts much longer and skip those tests on CRAN.

```r
  t_total > 10 && t_total < 19 is not TRUE
  
  `actual`:   FALSE
  `expected`: TRUE 
  ── Error (test-integration.R:147:5): Cancel and error handling ─────────────────
  Error: timeout reached when waiting for value: plot_run
  Backtrace:
      █
   1. └─FutureManager:::runClick(app, "plot_run") test-integration.R:147:4
   2.   └─app$waitForValue(...) test-integration.R:3:2
   3.     └─shinytest:::sd_waitForValue(...)
  
  [ FAIL 2 | WARN 0 | SKIP 0 | PASS 40 ]

```

**Comment by mjakubczak** [comment]
@zzawadz thank you for the PR; it looks like disabling the integration tests for CRAN makes sense here. 
Regarding timeouts: I think that the one you set is sufficient; longer timeouts mean longer wait until some test fails for a good reason

**Comment by zzawadz** [comment]
The other thing before CRAN release would be solving the multiprocess warning:
```
plan(multiprocess) # don't forget this line!
Strategy 'multiprocess' is deprecated in future (>= 1.20.0). Instead, explicitly specify either 'multisession' or 'multicore'. In the current R session, 'multiprocess' equals 'multisession'.[ONE-TIME WARNING] Forked processing ('multicore') is not supported when running R from RStudio because it is considered unstable. For more details, how to control forked processing or not, and how to silence this warning in future R sessions, see ?parallelly::supportsMulticore
```

The ugly idea might be as follows:
```
backend <- if(Sys.getenv("RSTUDIO") == "1") multisession else multicore 
plan(backend) # don't forget this line!
```

However, I think that it should use `multisession` by default (it is recommended), but it might be noted somewhere that for better performance `multicore` should be considered (it's the final note in `usage.Rmd`).

**Comment by mjakubczak** [comment]
I would wrap your idea into a function:

```
fmMultisession <- function(){
  if(Sys.getenv("RSTUDIO") == "1") future::multisession else future::multicore 
}
```

and then it could be used in an app as:

```
plan(fmMultisession())
```

Forked process starts immediately, which is a cool feature especially for large input data (no need to transfer the data to the child process). Without forking there's a noticeable lag when clicking the run button in such circumstances.

**Pull request merged**
